### ISSUE TITLE
Web frontend?

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#21]
Hi Magnus,

I'm not sure if this is of interest to you, but in case you have plans for a web frontend, this repo could be helpful:
https://github.com/miguelgrinberg/microdot

Maybe a web frontend could help the users to set some parameters if you plan such a feature in the future.

BTW, thinking beyond iNetBox, e.g. the spirit-level and Duo Control that you already included, why not try to plan for a customized modular board that could offer even more "gimmicks", e.g. sensors for water leakage, gas alarm, air humidity, air pressure in tires, etc.? ("Baukastensystem"?) Is it affordable for private customers to ask a company to develop and produce such boards?

**Comment by mc0110** [comment]
Hi ....., whats your name?
I'll try to bring you up to date. I have been trying to develop a web frontend for the last 2 weeks. With Miguel's help, I first did this in microdot, then transferred everything to the nanoweb framework. The frontend is now running after crash courses in CSS and Jquery. But there is no real use-case and unfortunately the upython resources are finite. So microdot does not run together with the inetbox2mqtt modules in memory.
So I'm not sure how many addons we can still get executable in memory, because the code is pulled into RAM during import.
What actually works for me, however, is the OTA update from the GITHUB. This makes the installation process much easier and possible without having to work with an IDE (e.g. Thonny). And you can also repeat this upload later if you have internet in the camper - which is what most people interested in these solutions have. 

The installation process with a terminal connection on a fresh microPython installation would take place like this. At the terminal, one enters the few lines of code at the *>>* prompt.

    >>>import network
    >>>s = network.WLAN(network.STA_IF)
    >>>s.active(True)
    >>>s.connect("<yourSSID>","<YourWifiPW>")
    >>>print('network config:', s.ifconfig())
    >>>mip.install("github:mc0110/inetbox2mqtt/source/bootloader/main.py","/")
    >>>import main

This gives you an internet connection and the bootloader script loads all modules onto the chip. After that, the module starts with the input of the credentials and, more recently, with the queries as to which add-ons are desired.

What do you think, is this a right way to go?

**Comment by mc0110** [comment]
The point is, you actually always need a terminal / galvanic connection first. Even webrepl does not run without entering the credentials. The way I am following at the moment is as follows:

- Install Micropython on the port 
- Wifi connection via terminal
- Loading the web application via terminal
- After starting the application all further adjustments via web frontend

What do you think? 

From my point of view it is relevant to realise the installation of the code without IDE installation, otherwise you can also do everything with Thonny.

**Comment by snipah** [comment]
I would like that process a lot. And after this you'd have to enter a web frontend for config, updates, etc. ?

**Comment by mc0110** [comment]
Hi Stan, and to anyone else who is interested!

I published the library [wifimanager](https://github.com/mc0110/wifimanager) today. It hasn't become as compact as I wanted it to be at the moment. But this version is executable and tested on two different ports (ESP32 and RPI pico W). 
**Features:** You can log in via the Wifi AP (without Internet) and then use the web frontend to enter the credentials. You can create 2 **credential-files** and then swap them. This is especially useful if you want to install at home, but want to start it in the rv afterwards. You also have the OTA function via the frontend. 
@skrebber wanted json-support for the credentials. This is also realised. 
What is not possible because of the size is to leave the web-fontend on during normal operation. So one of my questions is: Do you need a file manager feature, for example? I'm not sure. The advantage is, you can download py-files, modify and upload without terminal or thonny-connection, e.g. 
I am interested in your opinion. Does it make sense to go down that route? Do we want to implement this at inetbox2mqtt. Please give feedback.

**Comment by appi1** [comment]
Hello
That's great progress for the project and makes installation easier. Of course, a file manager would be a massive improvement, so that files can be replaced or edited without connecting the ESP32 via USB. If the function has room in memory, I would be excited about this possibility.
Thanks and regards

**Comment by mc0110** [comment]
Thanks for your feedback - at the moment this functionality is included!

**Comment by mc0110** [comment]
Hi Stan, 
first of all, thank you for the effort you have made and your feedback.
Your questions indicate that there are still some uncertainties. But I will answer them all together in your other post.

**Comment by mc0110** [comment]
The web frontend is now implemented, so the issue should be solved.
