### ISSUE TITLE
CP+ version

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#27]
Hi Magnus, I have C4.03.00 => 0050.00 on my CP+ display and wonder what is now the version of my CP+. I understand it is version 4, but what is the part after the version about that you can see after pressing the CP+ button? Does that number matter, too? Thank you!

**Comment by amaral989** [comment]
The number is the version firmware on the heater unit. 
![20230124_090400](https://user-images.githubusercontent.com/39887356/216989738-103d5f87-d441-4d54-9063-ea29e5b28142.jpg)

I have enclosed a picture of my firmware on the heater

**Comment by mc0110** [comment]
I have no idea! But what do you want to know for?

**Comment by mc0110** [comment]
Hi, 
thanks for the data - the heater version number is a surprise to me. But I have already been told that the newer CPplus can also support older Heater versions. 
With John's and Andy's help, we now also know that the CPplus must have at least major version number 4. Otherwise, unfortunately, there is no support or information from the manufacturer to help us.  
So no offence, but I support your view - don't change anything if it already works.
