### ISSUE TITLE
How to access ESP32 with inetbox2mqtt from remote?

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#37]
Hi Magnus,

I hope my message finds you well.

My spare ESP32 now runs `flash_esp32_inetbox2mqtt_v210_4M.bin`. It is connected to my Wifi at home, and I can see its IP on my Fritzbox. However, I cannot access any web GUI and assume that this is only available in OS mode. Is this correct? If yes, is there a way to get it back to OS mode from remote, or do I have to walk back to my car, unplug the ESP32 from the CP+/Truma, and bring it back to my PC?

Thanks for your help, and greetings
7wells

**Comment by mc0110** [comment]
Hi my friend,

the web GUI is, as correctly assumed, only accessible in OS mode. The MQTT connection can be used with the command
 
      topic: service/truma/set/os_run      payload:1 

OS mode will be reactivated. The ESP32 then reboots and starts with the web interface.

Best regards and a nice evening
M.

**Comment by mc0110** [comment]
Did you try to get a GUI answer, if you are in "Normal RUN". I assume, you won't get an answer. This is the normal behavior for ESP32 and RPI.

All in all, I'm not sure at the moment if it makes sense to make further cosmetic adjustments. Testing and quality assurance are really work-intensive and I haven't really received any feedback (except from you) for months. I lack motivation there. Besides, there is also an ESPHome version that Fabian built, but it uses different entities. So it's not convergence, but unfortunately, as is often the case, rather divergence. 

Since TRUMA has also discontinued CPplus, the whole project has no real future. I have had the 2.1 version running in my camper for several months without any problems. That was the real goal and it has been achieved.

**Comment by mc0110** [comment]
Stop experimenting. I can only recommend that. 

Thank you for the really great suggestions and I agree with you that there may be easier ways. I tried to make the whole thing as elegant and simple as possible in upython, but I admit that this may not have worked out optimally.
