### ISSUE TITLE
Credentials => Scan Wifis shows blank page

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#39]
Hi Magnus,

I'm still experimenting with the different versions of your tool and just flashed `flash_esp32_inetbox2mqtt_v15b_4M.bin` into my ESP32 with esptool. Then I entered 2 sets of Wifi credentials (for home and for car router, respectively) and successfully connected my ESP32 to my car router.

Maybe I do not yet fully understand all the functions of the ESP32 GUI. I wanted to see what "Scan Wifis" does, so went back to Credentials and clicked that button.

The page loads with http://192.168.4.1/scan?ButtonName=Scan+Wifis but remains blank.

Do you have a hint where I should have a second/more detailed look and what could be wrong? Furthermore, why would I need the "Scan Wifis" button (if it worked for me) - to connect to public Wifis when on the road?

As always, thanks a lot for your time and your help! 😃

**Comment by mc0110** [comment]
You should not experiment with different versions. I recommend the latest version. The GUI is only a help to enter the connection settings as quickly as possible. 

Sometimes it takes more than one call to the scan function and the result can take several seconds. But this is not due to the software but to the chips (in your case the ESP32).
