### ISSUE TITLE
Rx/Tx GPIO pins

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#4]
Hi Magnus!
I was unsure which GPIO pins of the ESP32 I need to connect, so I first looked into Daniel's project [readme](https://github.com/danielfett/inetbox.py#readme):
```
TX connects to GPIO 15 on the Raspberry Pi (RX).
RX connects to GPIO 14 on the Raspberry Pi (TX).
```

However, in your `truma_serv.py` I read this comment:

`# The communication with the CPplus uses ESP32-UART2 - connect (tx:GPIO17, rx:GPIO16)`

So, it should be these, right?

![1](https://user-images.githubusercontent.com/65889763/200802811-a72f905e-df5c-436f-82a1-02f3e0bd8109.png)

Not that I bother much, but I wonder if there is a reason for this difference. I ask also for my personal education. 😀

**Comment by mc0110** [comment]
I assume, you are joking......
Honestly, though, there are no bad questions, only bad answers!
Daniel uses a RPI board, you try to use a ESP32.
The ESP32 has 3 hardware-UARTS (0-2), all with programmable Pins. But the default for UART2 is tx-GPIO17, rx-GPIO16

**Comment by mc0110** [comment]
And yes, I confirm your adapted connection description

**Comment by mc0110** [comment]
So my answer is hopefully okay for you

**Comment by mc0110** [comment]
Short explanation of the connection - we can then also include it in our description:
LIN connection: Clearly speaking, an RJ11 cable is enough - only the inner cables are needed. In some cables, the wires are unfortunately swapped (especially in the splitters) because this is not critical for the telephone. I only found the LIN signal on the second try (Pin3 / Pin5 swapped).

TX and RX are correctly marked on your picture. The pins are also not critical against twisting (nothing will break). So just try it.

If you use the LEDs (see my instructions, but be sure to use a 300-600Ohm resistor), the GPIO12 will react immediately if the connection is correct and an Inetbox has already been connected. Otherwise, nothing happens until you have done Init once.

**Comment by mc0110** [comment]
> Is it correct that GND should be connected to a GND pin of the ESP32?

It must connected!

**Comment by mc0110** [comment]
No, no - it's OK!
Please give me a hint if your ESP32 has a LIN connection. That will be a reason to celebrate

**Comment by mc0110** [comment]
I am surprised and very sorry for you! 
There must be something wrong with the connection between CPplus and ESP32. 
To be honest, I always had the problem with Daniel's solution - I had also used an RPI at first - that there was no connection after a restart without an initial init. This was completely different with the ESP32. Since the routine reacts much faster, the init worked immediately if there were no electrical problems. I tested this several times. If the third entry is missing, then something is wrong electrically.
I have already had positive news from several testers in the last few days - the routine works.
I think, according to your hints - but this also corresponds to other user wishes, we have to work on the connectivity (credentials/ web server / MQTT). As far as I know, the LIN routine works great!

**Comment by mc0110** [comment]
Honestly, this is my first experience with a merge! Thanks for the effort and really great work.

**Comment by mc0110** [comment]
I approved your changes - thanks for that .... but more interesting for me
Is your LIN-connection online?

**Comment by mc0110** [comment]
Stop for a second and let's sum up:
Is Daniel's setup running now - have you tried again?
When Daniel's setup is running, you have only to connect 3 wires (GPIO16 /17 and GND) thats all. 
And if we disregard the leds, the box must then be recognised during an init.
Better still, if an init has been carried out with Daniel's box, then no new init is required. When the ESP32 is attached, everything works.

**Comment by mc0110** [comment]
> Daniel's program was working, yes, but with my RPi4, not with my ESP32. However, I cannot go back now, as my RPi4 now runs HA OS (and I don't plan to go back if I can avoid it).

Bad news - now I understand your comment yesterday

**Comment by mc0110** [comment]
The pictures look OK! Did the software run on the ESP32, did you see that on your computer? When you press RST on the ESP, the programme must start. The entry Lin-loop started is important.
If so, try the following procedure:
Switch on the ESP32 after you have established the LIN connection.
Then press the RST button on the ESP32 briefly (not the other button, please).
Then go to the RESET menu on the CPplus and perform INIT.
After a few seconds, the menu flickers and then returns to the normal display. Then the 3rd entry in the index must be found. I am keeping my fingers crossed

**Comment by mc0110** [comment]
Were you successful?

**Comment by mc0110** [comment]
I have been thinking about just that for a moment. The good news is that it indicates that your electrical connection is working. The error only occurs when the ESP32 receives control codes. So you're on the verge of a breakthrough.

About the error, I found it by random because I had compiled an upython kernel myself and used that version to develop the software and then I saw that on another chip (with the stable version from July) this error occurred. Hence my comment about the changes in upython itself that are yet to be seen.

**Comment by mc0110** [comment]
Why we should delete the "Alive-topic" logic?

**Comment by mc0110** [comment]
Yes, I was aware of that. Great work and thanks for sticking it out. I think all the comments are misleading, I need to revise that again.

I'm happy, that it is now running

**Comment by mc0110** [comment]
I am thinking about developing a circuit board for this application. You could participate ;-) 
I'll keep you informed!

**Comment by mc0110** [comment]
Smile! In your photos you can see the LIN connection with a brown cable and your connection to the ESP32 with a black cable. The two cables are connected on the LIN transceiver board. So you have a ground. All is OK!

**Comment by mc0110** [comment]
Hast Du versucht, etwas zu senden? Kannst Du die TRUMA steuern?

**Comment by mc0110** [comment]
Have you tried to send something? Can you control the TRUMA?

**Comment by mc0110** [comment]
There are sets that only work in combination. I had thought about including this, but it would be a change to Daniel's command set.
So temp_room can only be switched on in combination with heating_mode.
Simplest command is target_temp_water = 40 - I have always tested with this

**Comment by mc0110** [comment]
Okay, if you had display-status-messages with Daniel's RPI, then I'll go into the analysis again and see if I can find such messages with the RPI. But I can't remember them.
In my approach I never have seen them

**Comment by mc0110** [comment]
The control approach has been taken over 1:1 from Daniel. There is the following problem:
When you send a command, the command is transmitted to the CPplus. This means that the inetbox also writes the command to the MQTT server. In the result you see, for example, target_temp_room = 20. "APP" then appears in the CPplus display. If the CPplus does not accept the result, it overwrites the status after a while (1-2min) and target_temp_room = 0 appears again. If you wanted to change this, you would have to set up the software differently. So far I have avoided this - compatibility at the expense of user-friendliness.

**Comment by mc0110** [comment]
They are very much relevant when you set up the Home Assistant server. Then you do not need to define any entities, they will simply appear.

**Comment by mc0110** [comment]
I know - haven't seen them as mentioned. I will be searching - but it needs a few days
