### ISSUE TITLE
WiFi Password in fixed IP field

### ISSUE THREAD

**Issue by Carstens-Paulette** [mc0110/inetbox2mqtt#70]
Hello Magnus,

while setting up the debug for my lost connection issue, I found another annoying thing.

The fixedIP-Field is filled with the WiFi-password, althrough the system is not set to use it.

![Screenshot 2024-05-04 103935](https://github.com/mc0110/inetbox2mqtt/assets/167445387/b9e89e9a-7beb-437f-8868-d7ff952df67a)

Annotation: serial speed for WOMOLIN is 115.200 bps, just if anyondy is searching for it.

**Comment by mc0110** [comment]
Hi,

relax and let me explain it again. The system has been tested many times and works. I have tested the WoMoLin board here for weeks and if you set the HW setting in the args.dat correctly, the LAN connection will also work. You have a small error (the PW is printed in the DEBUG), but the IP is set correctly.

Enjoy and have fun

**Comment by Carstens-Paulette** [comment]
Hello Magnus,
sorry for getting me wrong.
The software is really good. 
If you already know about this, and it does not have any influence on the function, everything is okay.
I don't want to annoy to.

Kind regards

Carsten

**Comment by mc0110** [comment]
Most of the problems reported here are connection problems because, for example

- the broker is on the Internet
- a VPN connection is being used
- the MQTT server does not show a clean protocol
- encrypted connections (TLS) are to be used

None of this is covered by the software. My aim was to realise a solution that connects a broker located in the RV with the TRUMA.
